### PR TITLE
test: add vitest as test tool and increase test coverage

### LINKED ISSUE #12: Add Proper Unit Test Coverage
This issue is about getting to 90% coverage for the Permit CLI. The current tests use only Node test runner and do not pass completely, so the task is also to stabilize the tests and choose the right tooling for efficient unit test writing.

Acceptance Criteria:
* Consistlenlty passed unit tests that cover 90% of the code in the repository by the time of starting work on the issue
* Well-documented explanation of how to run and write the tests on the home page

### PR DESCRIPTION
**Pull request by varshith257**
Closes #12 
/claim #12

Test coverage increased to 85%. The coverage is majorly left out in the Login.tsx and Policy.tsx. There are errors in the flows of this files and needed fixes which I count as the out of scope of this bounty.

### CODE REVIEW

**Comment by varshith257** [comment]
@quest-bot loot #12

**Comment by varshith257** [comment]
Just couple of issues in login and logout tests. Fixing them

**Comment by gemanor** [comment]
Hey, why do you need to change the source to src? Is that automated cursor refactoring or something?

**Comment by varshith257** [comment]
@gemanor Yes! It has been renamed as per simplify long dir name and to follow simplier standard name

**Comment by gemanor** [comment]
@varshith257 we don't need this renaming, please revert and keep the code as is. The issue was to add text, not to rename folders.

**Comment by gemanor** [comment]
Is that maybe something made automatically by AI tools like cursor?

**Comment by varshith257** [comment]
@gemanor No! I have renamed it

**Comment by varshith257** [comment]
@gemanor Can you review it?

**Pull request closed without merging**
