### PR TITLE
Unit test for the components 

### LINKED ISSUE #12: Add Proper Unit Test Coverage
This issue is about getting to 90% coverage for the Permit CLI. The current tests use only Node test runner and do not pass completely, so the task is also to stabilize the tests and choose the right tooling for efficient unit test writing.

Acceptance Criteria:
* Consistlenlty passed unit tests that cover 90% of the code in the repository by the time of starting work on the issue
* Well-documented explanation of how to run and write the tests on the home page

### PR DESCRIPTION
**Pull request by Abiji-2020**
# Unit test for the components 
 ## Currently Pending components 
 - authCallbackServer in auth.js file
 - login and logout
# Coverage report 
image

/claim #12 
closes #12

### CODE REVIEW

**Comment by Abiji-2020** [comment]
@gemanor do we have to add unit test for the login component? As we are modifying yhe component itself in #13

**Comment by Abiji-2020** [comment]
closes #12 
/claim #12 
@quest-bot loot #12

**Comment by gemanor** [comment]
@Abiji-2020, yes, I would wait for https://github.com/permitio/permit-cli/pull/37 and then merge from main to ensure we have 90% coverage.
I'll let you know when mergin it.

**Comment by Abiji-2020** [comment]
> @Abiji-2020, yes, I would wait for #37 and then merge from main to ensure we have 90% coverage. I'll let you know when mergin it.

oh okayy,

**Comment by Abiji-2020** [comment]
@gemanor any updates on #37

**Comment by gemanor** [comment]
No, we still waiting for Jay to submit the CR changes

**Comment by Abiji-2020** [comment]
@gemanor do we need tests for the hooks??

**Comment by Abiji-2020** [comment]
image
image


All the components have their individual unit tests, and also the complete flow test by combining it, the major reduce in coverage is due to hooks and 
- https://github.com/permitio/permit-cli/blob/main/source/components/EnvSelectionWizard.tsx
- https://github.com/permitio/permit-cli/blob/main/source/components/WorkspaceSelector.tsx

even though they are commented they are included in the coverage

**Comment by gemanor** [comment]
You can remove these files @Abiji-2020

**Comment by gemanor** [comment]
And to your question, yes, hooks has critical logic in it. All the hooks that being used, should have tests

**Comment by Abiji-2020** [comment]
> And to your question, yes, hooks has critical logic in it. All the hooks that being used, should have tests

Will update by EOD

**Comment by Abiji-2020** [comment]
@gemanor added tests for the hooks, currently the coverage is at 88.8%, checking any way to increase as moslty done.

**Comment by Abiji-2020** [comment]
# coverage increased to 90%
@gemanor 
image
image

**Comment by Abiji-2020** [comment]
@gemanor could you take a look at this?

**Comment by gemanor** [comment]
Hey @Abiji-2020, the tests have not been passed on my local machine. Can you check that?

This is the result:
```
stderr | tests/logout.test.tsx > Logout > should render the logout component and call process.exit
Mocked process.exit(0)

 ✓ tests/SelectProject.test.tsx (4)
 ✓ tests/hooks/useAuthApi.test.tsx (4)
 ✓ tests/PDPCheck.test.tsx (4)
 ✓ tests/lib/auth.test.ts (9)
 ✓ tests/EnvCopy.test.tsx (3) 425ms
 ✓ tests/EnvMember.test.tsx (2) 331ms
 ✓ tests/EnvSelect.test.tsx (7) 533ms
 ✓ tests/LoginFlow.test.tsx (5)
 ✓ tests/OPAPolicy.test.tsx (2)
 ✓ tests/PDPCheck.test.tsx (4)
 ✓ tests/PDPRun.test.tsx (1)
 ✓ tests/SelectEnvironment.test.tsx (4)
 ✓ tests/SelectOrganisation.test.tsx (5) 337ms
 ✓ tests/SelectProject.test.tsx (4)
 ❯ tests/apiKey.test.tsx (4)
   ❯ ApiKey (4)
     ✓ Should save the key
     ✓ Should validate the key
     × Should read the key
     ✓ Invalid Key
 ✓ tests/cli.test.tsx (1)
 ✓ tests/github.test.tsx (16) 3995ms
 ✓ tests/index.test.tsx (1)
 ✓ tests/login.test.tsx (1)
 ✓ tests/logout.test.tsx (1)
 ✓ tests/components/AuthProvider.test.tsx (5)
 ✓ tests/components/EnvironmentSelection.test.tsx (1)
 ✓ tests/components/PDPCommand.test.tsx (2)
 ✓ tests/hooks/useApiKeyAPI.test.tsx (6) 323ms
 ✓ tests/hooks/useAuthApi.test.tsx (4)
 ✓ tests/hooks/useEnvironmentApi.test.tsx (5)
 ✓ tests/hooks/useMemberAPI.test.tsx (2)
 ✓ tests/hooks/useOrganizationAPI.test.tsx (4)
 ✓ tests/hooks/useProjectAPI.test.tsx (2)
 ✓ tests/lib/api.test.ts (1)
 ✓ tests/lib/auth.test.ts (9)
 ✓ tests/lib/gitops_utils.test.ts (7)
 ✓ tests/utils/attributes.test.ts (12)
```

**Comment by Abiji-2020** [comment]
> Hey @Abiji-2020, the tests have not been passed on my local machine. Can you check that?
> 
> This is the result:
> 
> ```
> stderr | tests/logout.test.tsx > Logout > should render the logout component and call process.exit
> Mocked process.exit(0)
> 
>  ✓ tests/SelectProject.test.tsx (4)
>  ✓ tests/hooks/useAuthApi.test.tsx (4)
>  ✓ tests/PDPCheck.test.tsx (4)
>  ✓ tests/lib/auth.test.ts (9)
>  ✓ tests/EnvCopy.test.tsx (3) 425ms
>  ✓ tests/EnvMember.test.tsx (2) 331ms
>  ✓ tests/EnvSelect.test.tsx (7) 533ms
>  ✓ tests/LoginFlow.test.tsx (5)
>  ✓ tests/OPAPolicy.test.tsx (2)
>  ✓ tests/PDPCheck.test.tsx (4)
>  ✓ tests/PDPRun.test.tsx (1)
>  ✓ tests/SelectEnvironment.test.tsx (4)
>  ✓ tests/SelectOrganisation.test.tsx (5) 337ms
>  ✓ tests/SelectProject.test.tsx (4)
>  ❯ tests/apiKey.test.tsx (4)
>    ❯ ApiKey (4)
>      ✓ Should save the key
>      ✓ Should validate the key
>      × Should read the key
>      ✓ Invalid Key
>  ✓ tests/cli.test.tsx (1)
>  ✓ tests/github.test.tsx (16) 3995ms
>  ✓ tests/index.test.tsx (1)
>  ✓ tests/login.test.tsx (1)
>  ✓ tests/logout.test.tsx (1)
>  ✓ tests/components/AuthProvider.test.tsx (5)
>  ✓ tests/components/EnvironmentSelection.test.tsx (1)
>  ✓ tests/components/PDPCommand.test.tsx (2)
>  ✓ tests/hooks/useApiKeyAPI.test.tsx (6) 323ms
>  ✓ tests/hooks/useAuthApi.test.tsx (4)
>  ✓ tests/hooks/useEnvironmentApi.test.tsx (5)
>  ✓ tests/hooks/useMemberAPI.test.tsx (2)
>  ✓ tests/hooks/useOrganizationAPI.test.tsx (4)
>  ✓ tests/hooks/useProjectAPI.test.tsx (2)
>  ✓ tests/lib/api.test.ts (1)
>  ✓ tests/lib/auth.test.ts (9)
>  ✓ tests/lib/gitops_utils.test.ts (7)
>  ✓ tests/utils/attributes.test.ts (12)
> ```

I guess you have not stored any key in the keychain so it is missing let me check and update that

**Comment by gemanor** [comment]
@Abiji-2020, I extend the delay and now it passed locally, but not in the CI
Can you please check what happen in the CI and fix it?

**Comment by Abiji-2020** [comment]
@gemanor the library we use for copying the ssh keys cannot run in the normal actions so for that to run properly I have created  a PR #44

**Comment by gemanor** [comment]
Can we mock it instead? Having CI private versions could lead to security vulnerabilities and it's anti-pattern

**Comment by Abiji-2020** [comment]
I have gone through it but it is a problem with the package `clipboardy` which we are using for copying there is also another solution that https://github.com/sindresorhus/clipboardy/issues/63#issuecomment-676484369

**Comment by gemanor** [comment]
It seems like it worked, but we still have problem with the keytar itself. Any idea?

**Comment by Abiji-2020** [comment]
we can install the libsecret-1.so.0 package in the ci? or else we need to mock keytar in all of them

**Comment by gemanor** [comment]
What could be the implication of installing it in the CI?

**Comment by gemanor** [comment]
I added it on main, so you can revert the ci changes you made..

**Comment by Abiji-2020** [comment]
All of them are working on the windows machine so let me check them and update them if any errors.

**Comment by gemanor** [comment]
Okay, now it all failed. I think it is better to mock the keytar functions too..

**Comment by gemanor** [comment]
I reverted the CI files, I think installing the lib-secret will just create more troubles. It's okay to mock the keytar IMO

**Comment by Abiji-2020** [comment]
@gemanor when running pdp check command in a linux machine it shows an error of 
image

**Comment by Abiji-2020** [comment]
@gemanor I have tried mocking the keytar but I am unable to process the issue 
`Error: Failed to execute child process “dbus-launch” (No such file or directory)`

which is requiring a headful environment to process.

**Comment by Abiji-2020** [comment]
> @Abiji-2020 please let me know when you have a version with keytar functions mocked, and I'll re-run the CI tests

ok @gemanor will update

**Comment by gemanor** [comment]
@Abiji-2020, this is a good progress, seems like we are mostly good with it

**Comment by Abiji-2020** [comment]
yes 3 more test files should be modified .

**Comment by Abiji-2020** [comment]
@gemanor updated and fixed CI

**Review by gemanor — APPROVED** [review]
LGTM

**Pull request merged**
